# Generated by Django 2.0.6 on 2018-06-25 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('lec_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semister_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.Attendance')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('roll_id', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(max_length=40)),
                ('roll_id', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=2)),
                ('batch', models.CharField(max_length=2)),
                ('batch_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('abr', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='semister_5',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.Student'),
        ),
        migrations.AddField(
            model_name='semister_5',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computer.Subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='computer.Student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sudject_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='computer.Subject'),
        ),
    ]
