# Generated by Django 2.0.6 on 2018-06-25 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semister_5',
            name='attendances',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='computer.Attendance'),
        ),
    ]
