# Generated by Django 2.0.6 on 2018-06-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_auto_20180626_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semister_5',
            name='attendances',
        ),
        migrations.RemoveField(
            model_name='semister_5',
            name='students',
        ),
        migrations.RemoveField(
            model_name='semister_5',
            name='subjects',
        ),
        migrations.AddField(
            model_name='student',
            name='semister',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='semister',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Semister_5',
        ),
    ]
