# Generated by Django 2.0.6 on 2018-06-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0003_auto_20180626_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semister',
            field=models.IntegerField(),
        ),
    ]
