# Generated by Django 2.0.6 on 2018-06-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0004_auto_20180626_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='start_time',
        ),
    ]
