# Generated by Django 2.0.6 on 2018-07-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0005_auto_20180629_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student_data',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_data',
            field=models.ManyToManyField(to='computer.Student'),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sudject_data',
        ),
        migrations.AddField(
            model_name='attendance',
            name='sudject_data',
            field=models.ManyToManyField(to='computer.Subject'),
        ),
    ]
