# Generated by Django 2.0.6 on 2018-07-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0006_auto_20180703_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='sudject_data',
            new_name='subject_data',
        ),
    ]
