# Generated by Django 2.0.6 on 2018-07-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0007_auto_20180703_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student_data',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject_data',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
