# Generated by Django 2.0.6 on 2018-07-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0014_auto_20180703_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_data', models.CharField(max_length=8)),
                ('lec_count', models.IntegerField()),
                ('student_data', models.CharField(max_length=10)),
            ],
        ),
    ]
